# 自动更新github pages的配置
language: node_js
node_js: stable
before_install: 
  - npm update -g npm
install: 
  - npm install
script: 
  - npm run lint && npm run build
after_script:
  - git clone "https://${GITHUB_TOKEN}@${PAGES_REF}" upper_repos
  - mkdir ./upper_repos/vue/
  - cp -fr ./build/* ./upper_repos/vue/
  - cd upper_repos
  - git add .
  - git commit -m 'auto build'
  - git push
cache:
  directories:
    - node_modules
