language: "node_js"
node_js: 
  - "4.4.5"
before_install: 
  - npm update -g npm@4.5.0
install: 
  - npm install
script: 
  - npm run lint && npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  file: build/*
  on:
    branch: master