language: "node_js"
node_js: 
  - "8.1.4"
before_install: 
  - npm update -g npm
install: 
  - npm install
script: 
  - npm run lint && npm run build
after_script:
  - cd dist
  - git init
  - git pull "https://${PAGES_REF}" master
  - git add .
  - git commit -m "Update pages"
  - git push "https://${PAGES_REF}" master
cache:
  directories:
    - node_modules
