language: "node_js"
node_js: 
  - "8.1.4"
before_install: 
  - npm update -g npm
install: 
  - npm install
script: 
  - npm run lint && npm run dist
after_script:
  - cd dist
  - git init
  - git add .
  - git commit -m "Update pages"
  - git push -f "https://${GITHUB_TOKEN}@${PAGES_REF}" master:master
cache:
  directories:
    - node_modules
